[programs.localnet]
hla = "B6gLd2uyVQLZMdC1s9C4WR7ZP9fMhJNh7WZYcsibuzN3"

[programs.devnet]
hla = "B6gLd2uyVQLZMdC1s9C4WR7ZP9fMhJNh7WZYcsibuzN3"

[programs.mainnet]
hla = "B6gLd2uyVQLZMdC1s9C4WR7ZP9fMhJNh7WZYcsibuzN3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "keys/wallet.json"

[scripts]
test = "mocha -t 1000000 tests/hla.ts"
