[programs.localnet]
ddca = "3nmm1awnyhABJdoA25MYVksxz1xnpUFeepJJyRTZfsyD"

[programs.devnet]
ddca = "3nmm1awnyhABJdoA25MYVksxz1xnpUFeepJJyRTZfsyD"

[programs.mainnet]
ddca = "3nmm1awnyhABJdoA25MYVksxz1xnpUFeepJJyRTZfsyD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
