---
json_rpc_url: "https://api.testnet.solana.com"
websocket_url: ""
keypair_path: keys/devnet-validator-keypair.json
address_labels:
  "11111111111111111111111111111111": System Program
commitment: confirmed